### ISSUE TITLE
Editorial: how should private methods and accessors be specified?

### ISSUE THREAD

**Issue by littledan** [littledan/proposal-private-methods#3]
In the current specification, the logic is that a private method is like a lexically scoped variable. In particular, the lexically scoped internal "private name" has an internal slot (never mutated) which contains the actual method or getter/setter pair.

If we switch to doing brand checks for methods, I see two ways we could spec this (thanks to @bakkot for discussing this with me earlier):
- **A parallel representation with brand, on top of lexical scoping**: In addition to the representation described above, each object could have an internal slot containing a List of Private Names, where each of these is the name of a method or accessor. Private names are added to the list just before field initializers run. When accessing a method or getter/setter pair, check the list first to see if the name is included, and throw a ReferenceError otherwise.
- **Non-writable private instance fields**: Here, a private method is just a private field which is non-writable. Maybe private fields would reuse the object infrastructure for property descriptors internally, even if that's not exposed to users. They would all hold the same function identity. For accessors, those would similarly be represented internally as (own) private fields which are accessors in the same list. The non-writability/non-configurability makes these shared-like, even if they are actually own.

Ultimately, the differences are unobservable, but might have implications for what one might expect to happen in future revisions of the language. Either way, all of the private methods have to be added before any of the instance methods, so that the private methods can be called from initializers which come earlier textually. Which is better?

cc @allenwb @erights

**Comment by erights** [comment]
Since the differences are unobservable, I like the second much more. The spec explains the user intuition that we must uphold. When given a choice, regularities in the spec should reflect regularities that we hope helps users understand. Everything else is (merely) optimization.

**Comment by littledan** [comment]
Specified as unwritable own private fields in https://github.com/littledan/proposal-private-methods/commit/1998ae5cecbef6a8ce341c3b24df5a537e380f8b .
