### ISSUE TITLE
Allowing access without invocation

### ISSUE THREAD

**Issue by bakkot** [littledan/proposal-private-methods#4]
I believe @allenwb is suggesting [here](https://github.com/littledan/proposal-private-methods/issues/1#issuecomment-312118571) that it should only be possible to *invoke* a private method, not to dereference it in general.

This is an interesting idea, whether or not it's what he meant to suggest. This is certainly something which could be enforced statically. It would make private methods even more static, which may be a benefit or a downside depending on your perspective. It would also avoid [this potential problem](https://github.com/littledan/proposal-private-methods/issues/1#issuecomment-312479569) where you might expect a brand check in two places.

If we didn't have spread arguments I'd be strongly opposed, because of the need for `this.#m.apply(this, args)`. But as it is I can't see much reason to allow dereference, except for symmetry with the rest of the language (which not a small reason). It does not cause any loss of functionality, since if someone *actually* wants a function object stored in a private field they are still free to specify that explicitly - `const f = function(){}; class A { #m = f; }`.

**Comment by littledan** [comment]
I think there are some real use cases for accessing but not invoking private methods. For example, don't you want to be able to do `#method.bind(this)`, or `[1, 2, 3].map(#add, this)`?

----

If we do type checking as described in #1, there are a couple times we could do it
1. When accessing it from the instance
2. When invoking the method
3. Both times

I was imagining that we would do the check only when accessing (1), but I'd be interested in hearing any arguments for another version. This would match up with the "it's just a non-writable private field" spec representation.

I don't think a check at the beginning of a method would really give enough information for JITs to rely on. For example, it could get an object as a receiver which is in the state of having the private methods but not the private fields (e.g., if you call a private method from an initializer), or it can be called on an initialized instance. Type feedback would be needed to get anywhere anyway.

**Comment by bakkot** [comment]
These days I've gotten used to using arrows in place of almost all standard library methods which manipulate the receiver, including `bind` and the second argument to `map`. But you're right, those are still part of the language, and probably shouldn't be made unusable.

**Comment by littledan** [comment]
OK, I'm pretty sure we want to allow access without invocation, so closing this bug.
